### ISSUE TITLE
Fix X64 when using "next" branch (see failed tests)

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#105] opened 2016-01-05 19:52 UTC
180 tests are failing as reported by 906011b2da4261af09b18f17d7c3393a89194b92 . This can't happen and should be fix.

Remember that if those tests fail on X64, they will probably not be correct either in PPC64.

**Comment by gut** [comment] 2016-01-05 21:19
Hint: the for-facebook-vasm branch (8def34bee9c7579e4f975d115889df1986f5ca7e) has just 1 test failing (quick/hhvm_client_mode.php)

**Comment by gut** [comment] 2016-01-08 13:13
The following tests are failing in X64:

```
hphp/test/quick/all_type_comparison_test.php
hphp/test/quick/asm_assert_t.hhas
hphp/test/quick/asm_dvinit.hhas
hphp/test/quick/asm_fault_endings.hhas
hphp/test/quick/asm_jumps.hhas
hphp/test/quick/asm_stack_depth_and_jmp.hhas
hphp/test/quick/asm_unusual_lifetimes.hhas
hphp/test/quick/bool_operations.hhas
hphp/test/quick/continuation_serialize.php
hphp/test/quick/dv_bf.php
hphp/test/quick/dv_ia.php
hphp/test/quick/fc_enum_5.php
hphp/test/quick/floatcmp.php
hphp/test/quick/hh_async_closure_return_type_1.php
hphp/test/quick/hh_async_return_type_3.php
hphp/test/quick/hh_closure_return_type_1.php
hphp/test/quick/hh_functions2.php
hphp/test/quick/hh_softtype4.php
hphp/test/quick/hh_typehint1.php
hphp/test/quick/impl_abstract_default_vals.php
hphp/test/quick/impl_abstract_dv_i_Int.php
hphp/test/quick/lambda1.php
hphp/test/quick/lambda7.php
hphp/test/quick/param-type.php
hphp/test/quick/parse_shapes.php
hphp/test/quick/profile/Setprofile_async.php
hphp/test/quick/rename_function.php
hphp/test/quick/resource.php
hphp/test/quick/set_toarray_warn.php
hphp/test/quick/simp-add-dbl.php
hphp/test/quick/typehint_arraykey.php
hphp/test/quick/verify-param-type.php
hphp/test/quick/abs_codegen.php
hphp/test/quick/asm_alias.hhas
hphp/test/quick/asm_bad_array_elem.hhas
hphp/test/quick/asm_dvinit_fault.hhas
hphp/test/quick/asm_fcall.hhas
hphp/test/quick/asm_newstructarray.hhas
hphp/test/quick/asm_switch.hhas
hphp/test/quick/asm_user_attrs.hhas
hphp/test/quick/ctor_param_promotion_genericgood.php
hphp/test/quick/dv_ab.php
hphp/test/quick/dv_bi.php
hphp/test/quick/dv_ib.php
hphp/test/quick/fc_enum_1.php
hphp/test/quick/fc_enum_6.php
hphp/test/quick/function_varargs.php
hphp/test/quick/generator_varargs.php
hphp/test/quick/hh_async_closure_return_type_2.php
hphp/test/quick/hh_closure_return_type_2.php
hphp/test/quick/hh_functions3.php
hphp/test/quick/hh_tuples.php
hphp/test/quick/hh_typehint2.php
hphp/test/quick/hopt-translator_unwind.hhas
hphp/test/quick/impl_abstract_dv_i_integer.php
hphp/test/quick/impl_abstract_dv_si.php
hphp/test/quick/jmpfuse.php
hphp/test/quick/lambda2.php
hphp/test/quick/lambda8.php
hphp/test/quick/nonstatic_invname.php
hphp/test/quick/parse_type_not_typedef.php
hphp/test/quick/strong_iter_await.php
hphp/test/quick/trailing_comma.php
hphp/test/quick/trailing_comma_bad6.php
hphp/test/quick/translator_unwind.hhas
hphp/test/quick/array_short_attributes.php
hphp/test/quick/asm_array.hhas
hphp/test/quick/asm_class.hhas
hphp/test/quick/asm_escape.hhas
hphp/test/quick/asm_hoistable_1.hhas
hphp/test/quick/asm_prop_init.hhas
hphp/test/quick/asm_trait.hhas
hphp/test/quick/bindg_weird.hhas
hphp/test/quick/debug_backtrace.php
hphp/test/quick/defaultVals.php
hphp/test/quick/dv_af.php
hphp/test/quick/dv_bs.php
hphp/test/quick/dv_if.php
hphp/test/quick/fc_enum_10.php
hphp/test/quick/fc_enum_7.php
hphp/test/quick/hh_async_closure_return_type_3.php
hphp/test/quick/hh_closure_return_type_3.php
hphp/test/quick/hh_type_args2.php
hphp/test/quick/hh_typehint3.php
hphp/test/quick/impl_abstract_dv_ia.php
hphp/test/quick/impl_abstract_dv_so.php
hphp/test/quick/lambda3.php
hphp/test/quick/no_more_id_crazy.php
hphp/test/quick/openssl_binarysafety.php
hphp/test/quick/raise_array_index_notice.php
hphp/test/quick/regpressure_bug.php
hphp/test/quick/trailing_comma_bad1.php
hphp/test/quick/asm_array_elem.hhas
hphp/test/quick/asm_closure.hhas
hphp/test/quick/asm_extnames.hhas
hphp/test/quick/asm_hoistable_2.hhas
hphp/test/quick/asm_ret_type.hhas
hphp/test/quick/asm_type.hhas
hphp/test/quick/class_abstract_final1.php
hphp/test/quick/constIntToString.php
hphp/test/quick/dv_ai.php
hphp/test/quick/dv_ca.php
hphp/test/quick/dv_is.php
hphp/test/quick/fc_enum_2.php
hphp/test/quick/fc_enum_8.php
hphp/test/quick/finally_break.php
hphp/test/quick/hh_async_return_type_0.php
hphp/test/quick/hh_classes.php
hphp/test/quick/hh_const_type.php
hphp/test/quick/hh_softtype1.php
hphp/test/quick/hh_type_args3.php
hphp/test/quick/hh_typehint4.php
hphp/test/quick/impl_abstract_dv_as.php
hphp/test/quick/impl_abstract_dv_id.php
hphp/test/quick/lambda4.php
hphp/test/quick/simp-sub-dbl.php
hphp/test/quick/asm_assert_optobj.hhas
hphp/test/quick/asm_cont.hhas
hphp/test/quick/asm_fatal_await.hhas
hphp/test/quick/asm_hoistable_3.hhas
hphp/test/quick/asm_sswitch.hhas
hphp/test/quick/asm_types.hhas
hphp/test/quick/cgetm_ge.php
hphp/test/quick/collection-exceptions.php
hphp/test/quick/ctor_param_promotion_attr.php
hphp/test/quick/debug_backtrace_multiline.php
hphp/test/quick/dv_as.php
hphp/test/quick/dv_ci.php
hphp/test/quick/dv_si.php
hphp/test/quick/fc_enum_3.php
hphp/test/quick/fc_enum_9.php
hphp/test/quick/guard-bug.php
hphp/test/quick/hh.php
hphp/test/quick/hh_async_return_type_1.php
hphp/test/quick/hh_classes2.php
hphp/test/quick/hh_extends.php
hphp/test/quick/hh_softtype2.php
hphp/test/quick/hh_type_args4.php
hphp/test/quick/hh_typehint5.php
hphp/test/quick/impl_abstract_dv_b_Bool.php
hphp/test/quick/impl_abstract_dv_io.php
hphp/test/quick/lambda5.php
hphp/test/quick/normalize.php
hphp/test/quick/pcre_limit.php
hphp/test/quick/test-withref.hhas
hphp/test/quick/typechecks-dv.php
hphp/test/quick/typehint_number.php
hphp/test/quick/xhp_attribute_type_mixed.php
hphp/test/quick/asm_assert_ref.hhas
hphp/test/quick/asm_declvars.hhas
hphp/test/quick/asm_fault.hhas
hphp/test/quick/asm_iterbreak.hhas
hphp/test/quick/asm_sswitch_slow.hhas
hphp/test/quick/asm_unnamed.hhas
hphp/test/quick/class_abstract_final3.php
hphp/test/quick/cnvBool.php
hphp/test/quick/collection-initializer.php
hphp/test/quick/const_exprs.php
hphp/test/quick/dec-minint.php
hphp/test/quick/dv_ba.php
hphp/test/quick/dv_si_func.php
hphp/test/quick/fc_enum_4.php
hphp/test/quick/fun_catch_block.php
hphp/test/quick/func_slice_args.php
hphp/test/quick/hh_async_closure_return_type_0.php
hphp/test/quick/hh_async_return_type_2.php
hphp/test/quick/hh_closure_return_type_0.php
hphp/test/quick/hh_functions.php
hphp/test/quick/hh_softtype3.php
hphp/test/quick/hh_type_var.php
hphp/test/quick/hhas_fc_enum.hhas
hphp/test/quick/impl_abstract_dv_b_boolean.php
hphp/test/quick/impl_abstract_dv_is.php
hphp/test/quick/lambda6.php
hphp/test/quick/no_return_function.php
hphp/test/quick/packed-isset.php
hphp/test/quick/pgo1.php
hphp/test/quick/reflection_is_async.php
hphp/test/quick/shapes_class_constant.php
hphp/test/quick/strict_hashbang_start.php
```

**Comment by gusbromero** [comment] 2016-01-08 20:20
The quick/hhvm_client_mode.php is also the only test that fails in FB master branch. So I think it's not a big concern by now. OTOH, if I noted it right, it seems some tests are failing in our next branch since fibonacci tag.

**Comment by gromero** [comment] 2016-01-08 21:43
All tests passed in our branch for-facebook-vasm on x64. The problem  with quick/hhvm_client_mode.php is an artifact. Removing /etc/hhvm/php.ini or passing --no-config to the test will solve the problem. The root cause is that some flag in php.ini (local settings) suppresses the error output when `hhvm <any wrong path you want>` is invoked. Since there is no output, there is nothing to compare against the .expect file,   thus the test fails.

**Comment by gromero** [comment] 2016-01-22 13:31
After fixing quick/hhvm_client_mode.php (already merged into FB master) and enabling allow_hhas (= true) & force_hh = (true) (ok after 55a8b13) all tests are passing. There was also an issue about building on x86, mostly related to namespace that is correct by now (e6cfce5). So, as I can't see any problem regarding building or testing on x64, I will close this issue.

**Closed as completed** 2016-01-26 15:56 UTC
Labels: bug, task
